### ISSUE TITLE
About the shape of the goal

### ISSUE THREAD

**Issue by yingnan-rl** [arrival-ltd/catalyst-rl-tutorial#4]
Thanks for your code. I have successfully launched your code. 
I still have two questions. 1. How to edit the "goal" in Coppeliasim? For example, I want change the shape of the goal's center, now is circle. I want to change it to triangle or rectangle, or other shapes. I found I can't edit this compound shape directly in Coppeliasim. How to create another new goal?
2. I noticed that the action space of UR5 is Three-dimensional, which is the goal position (x,y,z). Is there any possibility to change the control mode？For example, I want to control every joint of the UR5 instead of giving a target position.

**Comment by dtransposed** [comment]
1. I am not sure if the simulator provides a tool to create geometric objects. What I would advice you to do is to design the part in some CAD software (e.g. FreeCAD), export the model in the appropriate format (e.g. .stl) and eventually import it into Coppeliasim.
2. This is definitely possible (we have tried it internally). However, joint control mode is not available in this particular tutorial.
Still, this should be quite easy to implement by:
- changing the dimensionality of the action to the DoF of your robot (assuming revolute joints only).
- switching from cartesian tool control (and applying IK) to joint control in Coppeliasim. Certainly you will find appropriate tutorials on Coppeliasim website. We do not want to invest more time into this repository (we will maintain it though), so I doubt that we will be adding this feature in the near future.

**Comment by yingnan-rl** [comment]
Thanks for your reply!

**Comment by dtransposed** [comment]
You are welcome! I'm closing the issue.
