### ISSUE TITLE
how to implement it on real system? 

### ISSUE THREAD

**Issue by abdul-mannan-khan** [arrival-ltd/catalyst-rl-tutorial#6]
My question is regarding its implementation. How can we implement it on real robot? Could you also please provide some description. 

It is very interesting simulation example and it is highly appreciated. 

Thank you for sharing.

**Comment by fedor-chervinskii** [comment]
Hi @abdul-mannan-khan, thanks for your interest in our work. Here we intentionally do not share here the implementation for testing this on a real robot, however, you can find it in our [Medium post](https://medium.com/pytorch/robotic-assembly-using-deep-reinforcement-learning-dfd9916c5ad7) that we did tests on the real robot (in our case UR-5).

Although we can't share the implementation here, what you can do basically is to write another `environment` class that will wrap around the API calls for the robot. (a good example of wrapping around UR-5 can be found for example in [this repo](https://github.com/andyzeng/visual-pushing-grasping) Then, after training an agent to perform well on a simulation environment, using Catalyst you can roll out your trained agent on the "Real" environment, so the agent will send commands to the real robot.

Hope this helps, let me know if any more questions.
And good luck!
